version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: work_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/work_tracker
      RUST_LOG: info
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/backend
      - ./shared:/shared

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/frontend
      - ./shared:/shared
    depends_on:
      - backend

volumes:
  postgres_data: